### PR TITLE
Refactor connect uber

### PR DESCRIPTION
**Pull request by EdmundLeex**

### CODE REVIEW

**Comment by EdmundLeex** [comment]
shall we merge this?

**Comment by AnOctopus** [comment]
Assign someone other than me to look over it, if you like. It's not a big change.

**Comment by AnOctopus** [comment]
Can we resolve this?

**Comment by EdmundLeex** [comment]
You mean closing the issue?

Edmund Li

**Comment by AnOctopus** [comment]
It should be mergable, but I wanted someone to verify it.

**Comment by EdmundLeex** [comment]
We should finish all test first I think

Edmund Li

**Comment by EdmundLeex** [comment]
need to resolve conflicts

**Pull request merged**
